### PR TITLE
MGMT-15757: Provide a more detailed description of the BugMasterBot

### PR DESCRIPTION
**Pull request by danmanor**
Provide a more detailed description of the `BugMasterBot`.

### CODE REVIEW

**Comment by rccrdpccl** [comment]
@danmanor should we merge or close this one?

**Comment by danmanor** [comment]
@eliorerz Can you please review ?

**Comment by danmanor** [comment]
OK lets merge this one @rccrdpccl 
@eliorerz when you have time to review this let me know if you have remarks, I will add changes

**Pull request merged**
